# language: python

# python:
#   - "2.7"
#   - "3.5"
#   - "3.6"
#   - "3.7"

# addons:
#     apt:
#         packages:
#             - ffmpeg

# install:
#   - pip install tox

# script: nosetests --with-coverage --cover-package=pya


language: python
python:
- "2.7"
- "3.5"
- "3.6"
- "3.7"
install:
- pip install python-coveralls coverage
- pip install -r requirements.txt
- pip install -r requirements_diagrams.txt
- pip install -r requirements_test.txt
script: nosetests --with-coverage --with-doctest
after_success:
- coveralls --config_file .coveragerc
addons:
  apt:
    packages:
      - ffmpeg